service: mi-api-serverless

provider:
  name: aws
  # runtime: nodejs14.x
  runtime: nodejs18.x
  # region: tu-region-aws # Reemplaza con tu región de AWS
  httpApi:
    timeout: 20

functions:
  getEndpoint:
    handler: handler.getEndpoint
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: /get-data
          method: get
          cors: true

  postEndpoint:
    handler: handler.postEndpoint
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: /create-data
          method: post
          cors: true
  helloEndpoint:
    handler: handler.getPersonaEndpoint
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: /get-persona
          method: get
          cors: true

plugins:
  - serverless-offline # Para probar localmente
